/**
 * Mobility Scooter Assessment Form
 * Based on NDIS Assistive Technology Assessment Guidelines and Australian Standards AS 3695
 * Compliant with aged care and NDIS legislation for mobility equipment prescription
 */

import type { AssessmentSection } from "./assessmentForm";

export const MOBILITY_SCOOTER_ASSESSMENT: AssessmentSection[] = [
  {
    id: "client_assessment",
    title: "Client Assessment",
    description: "Comprehensive evaluation of client needs and capabilities",
    icon: "user",
    questions: [
      {
        id: "scooter_1",
        question: "What is the primary purpose for the mobility scooter?",
        description: "Indoor use, outdoor use, or both",
        type: "multiple_choice",
        options: ["Indoor only", "Outdoor only", "Indoor and outdoor", "Community access"],
        requiresMedia: false,
        aiPrompt: "Analyze the client's stated purpose for the mobility scooter. Consider their lifestyle, community participation goals, and NDIS reasonable and necessary criteria. Recommend appropriate scooter class and features.",
      },
      {
        id: "scooter_2",
        question: "What is the client's current mobility level?",
        type: "multiple_choice",
        options: ["Walks independently", "Uses walking aid", "Wheelchair user", "Limited walking distance"],
        requiresMedia: false,
        aiPrompt: "Assess the client's baseline mobility. Determine if a scooter is the most appropriate mobility aid or if other options should be considered. Evaluate for NDIS funding eligibility.",
      },
      {
        id: "scooter_3",
        question: "Can the client safely transfer on/off the scooter independently?",
        description: "Critical safety requirement",
        type: "yes_no",
        requiresMedia: true,
        aiPrompt: "Observe the client's transfer technique in this video/photo. Assess balance, strength, coordination, and safety. Identify fall risks and recommend training or modifications if needed.",
      },
      {
        id: "scooter_4",
        question: "Does the client have adequate upper body strength and range of motion for scooter operation?",
        type: "yes_no",
        requiresMedia: true,
        aiPrompt: "Evaluate upper body function for scooter control. Can they reach and operate controls, turn the tiller, and maintain posture? Recommend adaptive controls if needed.",
      },
      {
        id: "scooter_5",
        question: "Does the client have adequate vision for safe outdoor navigation?",
        type: "yes_no",
        requiresMedia: false,
        aiPrompt: "Assess visual acuity and field of vision. Can they see obstacles, traffic, and pedestrians? Are there visual impairments that require additional safety features or training?",
      },
      {
        id: "scooter_6",
        question: "Does the client demonstrate adequate cognitive function for safe scooter operation?",
        description: "Judgment, decision-making, safety awareness",
        type: "yes_no",
        requiresMedia: false,
        aiPrompt: "Evaluate cognitive capacity for safe scooter use. Can they make safe decisions, respond to hazards, follow traffic rules, and understand operational limits? Document any concerns.",
      },
      {
        id: "scooter_7",
        question: "What is the client's weight and height?",
        description: "Required for appropriate scooter selection",
        type: "text",
        requiresMedia: false,
        aiPrompt: "Review client anthropometrics. Ensure scooter selection meets weight capacity (typically 115-160kg) and provides appropriate seat dimensions, leg room, and postural support.",
      },
    ],
  },
  {
    id: "environmental_assessment",
    title: "Environmental Assessment",
    description: "Evaluate home and community environment for scooter use",
    icon: "home",
    questions: [
      {
        id: "scooter_env_1",
        question: "Is there adequate storage space for the scooter at home?",
        description: "Consider charging access and weather protection",
        type: "yes_no",
        requiresMedia: true,
        aiPrompt: "Assess storage location in this image. Is there space for the scooter, access to power for charging, and protection from weather? Measure dimensions and recommend modifications if needed.",
      },
      {
        id: "scooter_env_2",
        question: "Are doorways wide enough for scooter access (minimum 760mm)?",
        type: "yes_no",
        requiresMedia: true,
        aiPrompt: "Measure doorway widths visible in this image. Standard scooters require 760-850mm clearance. Identify narrow access points and recommend widening or alternative access routes.",
      },
      {
        id: "scooter_env_3",
        question: "Are there ramps or level access to the home?",
        type: "yes_no",
        requiresMedia: true,
        aiPrompt: "Evaluate entry/exit access for scooter. Are there steps requiring ramps? Assess slope gradients (1:14 max for AS 1428.1). Calculate ramp requirements or recommend alternative solutions.",
      },
      {
        id: "scooter_env_4",
        question: "Are floors and surfaces suitable for scooter use?",
        description: "Carpet pile height, thresholds, surface transitions",
        type: "yes_no",
        requiresMedia: true,
        aiPrompt: "Analyze floor surfaces and transitions. Check carpet pile height (<13mm), thresholds (<20mm), and surface changes. Identify obstacles that may impede scooter operation.",
      },
      {
        id: "scooter_env_5",
        question: "Is there adequate turning space in rooms (minimum 1500mm diameter)?",
        type: "yes_no",
        requiresMedia: true,
        aiPrompt: "Assess room layouts and turning circles. Class 2 scooters typically need 1500mm turning space. Measure key areas and recommend furniture rearrangement or alternative routing.",
      },
      {
        id: "scooter_env_6",
        question: "Are pathways and footpaths in the local area suitable for scooter use?",
        type: "yes_no",
        requiresMedia: true,
        aiPrompt: "Evaluate community pathways for scooter accessibility. Check for curb ramps, surface quality, width, slopes, and obstacles. Document barriers to community participation.",
      },
      {
        id: "scooter_env_7",
        question: "Is there vehicle access for scooter transport if required?",
        type: "yes_no",
        requiresMedia: true,
        aiPrompt: "Assess transportation needs. Does the client need to transport the scooter? Evaluate vehicle type, hoist requirements, and recommend portable vs. non-portable scooter options.",
      },
    ],
  },
  {
    id: "scooter_selection",
    title: "Scooter Specification",
    description: "Determine appropriate scooter class and features",
    icon: "settings",
    questions: [
      {
        id: "scooter_spec_1",
        question: "What scooter class is appropriate based on usage environment?",
        description: "Class 1 (indoor), Class 2 (footpath), Class 3 (road)",
        type: "multiple_choice",
        options: ["Class 1 - Indoor only (max 10 km/h)", "Class 2 - Footpath use (max 10 km/h)", "Class 3 - Road use (max 10 km/h)"],
        requiresMedia: false,
        aiPrompt: "Based on the client's environment and usage patterns, recommend the appropriate scooter class under Australian road rules. Consider safety, regulations, and NDIS funding guidelines.",
      },
      {
        id: "scooter_spec_2",
        question: "What is the required range/battery capacity?",
        description: "Based on typical daily travel distances",
        type: "text",
        requiresMedia: false,
        aiPrompt: "Calculate required battery range based on the client's daily activities and distances. Standard ranges are 15-50km. Consider charging access and recommend appropriate battery capacity.",
      },
      {
        id: "scooter_spec_3",
        question: "Are 3-wheel or 4-wheel configuration more appropriate?",
        description: "3-wheel: tighter turning; 4-wheel: more stable",
        type: "multiple_choice",
        options: ["3-wheel (smaller turning circle)", "4-wheel (enhanced stability)"],
        requiresMedia: false,
        aiPrompt: "Recommend wheel configuration based on environment and client needs. 3-wheel scooters have tighter turning (indoor use) but 4-wheel provides better outdoor stability and weight capacity.",
      },
      {
        id: "scooter_spec_4",
        question: "What seating features are required?",
        description: "Captain's seat, swivel, adjustability, arms",
        type: "text",
        requiresMedia: false,
        aiPrompt: "Specify seating requirements based on client's postural needs, transfer method, and comfort. Consider seat width, depth, height adjustability, swivel function, and armrest type.",
      },
      {
        id: "scooter_spec_5",
        question: "Are additional safety features required?",
        description: "Lights, horn, indicators, mirrors, suspension",
        type: "text",
        requiresMedia: false,
        aiPrompt: "Identify necessary safety features. For road/outdoor use: headlights, tail lights, indicators, mirrors, horn. For all scooters: anti-tip wheels, electromagnetic brakes. Assess suspension needs.",
      },
      {
        id: "scooter_spec_6",
        question: "Are there specific storage or accessory requirements?",
        description: "Baskets, oxygen holder, crutch holder",
        type: "text",
        requiresMedia: false,
        aiPrompt: "Document accessory needs based on client's lifestyle. Common additions: front/rear baskets, oxygen tank holder, crutch/walker holder, weather canopy, USB charging port.",
      },
    ],
  },
  {
    id: "safety_training",
    title: "Safety & Training",
    description: "Safety assessment and training requirements",
    icon: "shield-check",
    questions: [
      {
        id: "scooter_safety_1",
        question: "Has the client demonstrated safe operation of the scooter controls?",
        type: "yes_no",
        requiresMedia: true,
        aiPrompt: "Observe scooter operation in this video. Assess control of speed, steering, braking, and reversing. Document any difficulties and recommend additional training or control modifications.",
      },
      {
        id: "scooter_safety_2",
        question: "Can the client safely navigate slopes and inclines?",
        description: "Maximum safe gradient is typically 1:14 (4 degrees)",
        type: "yes_no",
        requiresMedia: true,
        aiPrompt: "Evaluate slope navigation skills and local terrain. Can they safely ascend/descend slopes? Are there steep areas to avoid? Provide training recommendations and identify no-go zones.",
      },
      {
        id: "scooter_safety_3",
        question: "Has the client been trained in safe battery charging procedures?",
        type: "yes_no",
        requiresMedia: false,
        aiPrompt: "Confirm battery safety training. Client must understand: daily charging, use of correct charger, ventilation requirements, fire safety, and battery maintenance. Document training provided.",
      },
      {
        id: "scooter_safety_4",
        question: "Does the client understand when NOT to use the scooter?",
        description: "Weather conditions, terrain, after medication/alcohol",
        type: "yes_no",
        requiresMedia: false,
        aiPrompt: "Assess client's understanding of unsafe conditions: wet weather (reduced traction), uneven terrain, after sedating medications, poor visibility, excessive slopes. Document education provided.",
      },
      {
        id: "scooter_safety_5",
        question: "Has a maintenance schedule been established?",
        description: "Regular servicing as per AS 3695",
        type: "yes_no",
        requiresMedia: false,
        aiPrompt: "Establish maintenance plan per AS 3695.2. Annual servicing by qualified technician, regular battery checks, tire pressure, brakes, lights. Provide maintenance schedule and supplier contact.",
      },
      {
        id: "scooter_safety_6",
        question: "Is the scooter covered by appropriate insurance?",
        type: "yes_no",
        requiresMedia: false,
        aiPrompt: "Confirm insurance requirements. Third-party liability insurance recommended for road use. Check if home and contents covers scooter. Provide insurance guidance and resources.",
      },
    ],
  },
  {
    id: "ndis_justification",
    title: "NDIS Funding Justification",
    description: "Documentation for NDIS funding application",
    icon: "file-text",
    questions: [
      {
        id: "scooter_ndis_1",
        question: "How does the scooter meet 'reasonable and necessary' criteria?",
        description: "Relate to participant's goals and NDIS plan",
        type: "text",
        requiresMedia: false,
        aiPrompt: "Draft justification for NDIS funding. Explain how scooter: (1) relates to participant's disability, (2) enables goal achievement, (3) represents value for money, (4) is most appropriate solution, (5) enables community participation per NDIS Act 2013.",
      },
      {
        id: "scooter_ndis_2",
        question: "What participant goals will the scooter support?",
        description: "Link to NDIS plan goals",
        type: "text",
        requiresMedia: false,
        aiPrompt: "Identify specific NDIS plan goals addressed by the scooter. Examples: increased community participation, employment/education access, reduced carer burden, improved health outcomes through outdoor activity.",
      },
      {
        id: "scooter_ndis_3",
        question: "Have alternative options been considered and ruled out?",
        description: "Document assessment of other mobility aids",
        type: "text",
        requiresMedia: false,
        aiPrompt: "Document alternative mobility aids considered (manual wheelchair, power wheelchair, walking aids). Explain why scooter is most appropriate based on client's needs, environment, and goals.",
      },
      {
        id: "scooter_ndis_4",
        question: "What is the expected lifespan and value for money?",
        type: "text",
        requiresMedia: false,
        aiPrompt: "Justify cost-effectiveness. Standard scooter lifespan: 5-7 years with proper maintenance. Calculate cost per year and compare to transport alternatives, carer support costs, and community participation benefits.",
      },
      {
        id: "scooter_ndis_5",
        question: "Are there any risks if the scooter is NOT provided?",
        type: "text",
        requiresMedia: false,
        aiPrompt: "Assess consequences of not providing scooter. Consider: social isolation, inability to access services, increased carer burden, reduced independence, potential decline in physical/mental health, impact on NDIS goals.",
      },
    ],
  },
];

// Helper to get total questions for mobility scooter assessment
export const getMobilityScooterQuestionCount = (): number => {
  return MOBILITY_SCOOTER_ASSESSMENT.reduce((sum, section) => sum + section.questions.length, 0);
};
